### ISSUE TITLE
PyPI 패키지 배포

### ISSUE THREAD

**Issue by LeeHanYeong** [coolsms/coolsms-python#4]
구버전은 PyPI에 배포되어있었는데, 이 버전도 pip install로 설치할 수 있도록 배포예정은 없나요?

**Comment by Palbahngmiyine** [comment]
안녕하세요, 해당 사항의 경우 예정에는 있지만 구체적인 일정이 별도로 정해진 사항은 없습니다. 다만, 말씀해주신 사항을 최대한 반영하여 빠르게 pip 패키지로 이용하실 수 있도록 노력하겠습니다. 감사합니다.
